import { useState } from "react";
import Square from "./Square";
// import MovePanel from "./(panels)/MovePanel";
import ButtonPanel from "./(panels)/ButtonPanel";
// import { minWidth, width } from "@mui/system";
import RulesPanel from "./(panels)/RulesPanel";

function defaultBoard(): number[][] {
  let board: number[][] = []
  for (let i = 0; i < 15; i++) {
    board.push([]) 
    for (let j = 0; j < 15; j++) {
      board[i].push(0)
    }
  }
  return board
}


export default function Board() {
  const [player, setPlayer] = useState(false);
  const [moveList, setMoveList] = useState([])
  const [board, setBoard] = useState(defaultBoard())
  const [hasWinner, setHasWinner] = useState(false)
  const [winner, setWinner] = useState("")
  // const moves = moveList.map((move) => <p>{move}</p>)
  // console.log(board)
  const BOARD_WIDTH  = 24*15
  const BOARD_HEIGHT = 24*15

  return (
    <div id='game-container' className="grid grid-cols-3 justify-center items-center text-center w-screen">
      <RulesPanel/>
      <div id='board' className={`w-[${BOARD_WIDTH}px] min-w-[${BOARD_WIDTH}px] h-[${BOARD_HEIGHT}px] min-h-[${BOARD_HEIGHT}px] gap-y-0`}>
      <div id='current-player-display' className="text-center left-0 right-0 m-auto">
        <h1 className="text-2xl font-bold">Gomoku</h1>
        {hasWinner ? `${winner} wins!` : player ? "White to play." : "Black to play."}
      </div>
        <div className="board-row">
              <Square rowId={0} columnId={0} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={0} columnId={1} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={0} columnId={2} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={0} columnId={3} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={0} columnId={4} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={0} columnId={5} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={0} columnId={6} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={0} columnId={7} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={0} columnId={8} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={0} columnId={9} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={0} columnId={10} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={0} columnId={11} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={0} columnId={12} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={0} columnId={13} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={0} columnId={14} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
            </div>
            <div id="board-row-1" className="board-row">
            <Square rowId={1} columnId={0} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={1} columnId={1} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={1} columnId={2} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={1} columnId={3} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={1} columnId={4} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={1} columnId={5} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={1} columnId={6} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={1} columnId={7} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={1} columnId={8} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={1} columnId={9} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={1} columnId={10} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner} />
              <Square rowId={1} columnId={11} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={1} columnId={12} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={1} columnId={13} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={1} columnId={14} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
            </div>
            <div id="board-row-2" className="board-row">
            <Square rowId={2} columnId={0} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={2} columnId={1} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={2} columnId={2} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={2} columnId={3} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={2} columnId={4} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={2} columnId={5} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={2} columnId={6} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={2} columnId={7} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={2} columnId={8} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={2} columnId={9} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={2} columnId={10} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={2} columnId={11} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={2} columnId={12} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={2} columnId={13} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={2} columnId={14} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
            </div>
            <div id="board-row-3" className="board-row">
            <Square rowId={3} columnId={0} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={3} columnId={1} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={3} columnId={2} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={3} columnId={3} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={3} columnId={4} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={3} columnId={5} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={3} columnId={6} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={3} columnId={7} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={3} columnId={8} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={3} columnId={9} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={3} columnId={10} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={3} columnId={11} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={3} columnId={12} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={3} columnId={13} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={3} columnId={14} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
            </div>
            <div id="board-row-2" className="board-row">
            <Square rowId={4} columnId={0} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={4} columnId={1} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={4} columnId={2} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={4} columnId={3} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={4} columnId={4} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={4} columnId={5} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={4} columnId={6} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={4} columnId={7} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={4} columnId={8} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={4} columnId={9} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={4} columnId={10} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={4} columnId={11} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={4} columnId={12} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={4} columnId={13} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={4} columnId={14} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
            </div>
            <div id="board-row-1" className="board-row">
            <Square rowId={5} columnId={0} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={5} columnId={1} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={5} columnId={2} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={5} columnId={3} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={5} columnId={4} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={5} columnId={5} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={5} columnId={6} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={5} columnId={7} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={5} columnId={8} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={5} columnId={9} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={5} columnId={10} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={5} columnId={11} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={5} columnId={12} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={5} columnId={13} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={5} columnId={14} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
            </div>
            <div id="board-row-1" className="board-row">
            <Square rowId={6} columnId={0} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={6} columnId={1} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={6} columnId={2} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={6} columnId={3} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={6} columnId={4} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={6} columnId={5} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={6} columnId={6} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={6} columnId={7} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={6} columnId={8} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={6} columnId={9} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={6} columnId={10} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={6} columnId={11} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={6} columnId={12} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={6} columnId={13} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={6} columnId={14} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
            </div>
            <div id="board-row-1" className="board-row">
            <Square rowId={7} columnId={0} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={7} columnId={1} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={7} columnId={2} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={7} columnId={3} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={7} columnId={4} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={7} columnId={5} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={7} columnId={6} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={7} columnId={7} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={7} columnId={8} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={7} columnId={9} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={7} columnId={10} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={7} columnId={11} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={7} columnId={12} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={7} columnId={13} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={7} columnId={14} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList} currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
            </div>
            <div id="board-row-1" className="board-row">
            <Square rowId={8} columnId={0} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={8} columnId={1} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={8} columnId={2} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={8} columnId={3} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={8} columnId={4} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={8} columnId={5} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={8} columnId={6} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={8} columnId={7} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={8} columnId={8} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={8} columnId={9} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={8} columnId={10} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={8} columnId={11} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={8} columnId={12} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={8} columnId={13} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={8} columnId={14} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
            </div>
            <div id="board-row-1" className="board-row">
            <Square rowId={9} columnId={0} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={9} columnId={1} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={9} columnId={2} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={9} columnId={3} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={9} columnId={4} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={9} columnId={5} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={9} columnId={6} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={9} columnId={7} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={9} columnId={8} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={9} columnId={9} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={9} columnId={10} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={9} columnId={11} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={9} columnId={12} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={9} columnId={13} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={9} columnId={14} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
            </div>
            <div id="board-row-1" className="board-row">
            <Square rowId={10} columnId={0} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={10} columnId={1} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={10} columnId={2} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={10} columnId={3} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={10} columnId={4} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={10} columnId={5} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={10} columnId={6} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={10} columnId={7} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={10} columnId={8} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={10} columnId={9} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={10} columnId={10} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={10} columnId={11} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={10} columnId={12} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={10} columnId={13} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={10} columnId={14} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
            </div>
            <div id="board-row-1" className="board-row">
            <Square rowId={11} columnId={0} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={11} columnId={1} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={11} columnId={2} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={11} columnId={3} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={11} columnId={4} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={11} columnId={5} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={11} columnId={6} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={11} columnId={7} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={11} columnId={8} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={11} columnId={9} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={11} columnId={10} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={11} columnId={11} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={11} columnId={12} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={11} columnId={13} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={11} columnId={14} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
            </div>
            <div id="board-row-1" className="board-row">
            <Square rowId={12} columnId={0} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={12} columnId={1} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={12} columnId={2} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={12} columnId={3} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={12} columnId={4} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={12} columnId={5} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={12} columnId={6} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={12} columnId={7} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={12} columnId={8} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={12} columnId={9} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner} />
              <Square rowId={12} columnId={10} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={12} columnId={11} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={12} columnId={12} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={12} columnId={13} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={12} columnId={14} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
            </div>
            <div id="board-row-1" className="board-row">
            <Square rowId={13} columnId={0} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={13} columnId={1} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={13} columnId={2} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={13} columnId={3} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={13} columnId={4} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={13} columnId={5} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={13} columnId={6} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={13} columnId={7} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={13} columnId={8} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={13} columnId={9} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={13} columnId={10} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={13} columnId={11} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={13} columnId={12} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={13} columnId={13} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={13} columnId={14} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
            </div>
            <div id="board-row-1" className="board-row">
            <Square rowId={14} columnId={0} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={14} columnId={1} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={14} columnId={2} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={14} columnId={3} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={14} columnId={4} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={14} columnId={5} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={14} columnId={6} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={14} columnId={7} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={14} columnId={8} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={14} columnId={9} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={14} columnId={10} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={14} columnId={11} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={14} columnId={12} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={14} columnId={13} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
              <Square rowId={14} columnId={14} currentPlayer={player} updatePlayer={setPlayer} currentMoveList={moveList} updateMoveList={setMoveList}  currentBoard={board} updateBoard={setBoard} currentHasWinner={hasWinner} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
            </div>
             <ButtonPanel updatePlayer={setPlayer} updateBoard={setBoard} updateWinner={setWinner} updateHasWinner={setHasWinner}/>
      </div>
        {/* <div className="w-fit bg-gray-50 border border-1 border-black max-h-44 overflow-y-auto left-0 right-0 m-auto">
          {moves}
        </div> */}
    </div>
  );
}
